[phases.setup]
nixPkgs = ['nodejs_18', 'php81', 'php81Packages.composer']

[phases.install]
cmds = [
    'npm ci --only=production',
    'composer install --optimize-autoloader --no-dev'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'